volumes:
  pgdata:

services:
  python:
#    image: python:3.9
    build:
      context: .
      dockerfile: Dockerfile
    volumes:  # mounting data to docker. Volume for sqlite
      - .:/ecommerce_platform
    ports:
      - 8000:8000
    command: bash -c 'while !</dev/tcp/postgres/5432; do sleep 5; done; python manage.py runserver 0.0.0.0:8000'
    depends_on:
      - postgres
      - rabbitmq

  postgres:
    image: postgres:14
    environment:
      POSTGRES_DB: test_ecommerce_db
      POSTGRES_USER: test_ecommerce
      POSTGRES_PASSWORD: test_ecommerce

    ports:
      - 5432:5432

    volumes:  # Use script to initialize db, mount pgdata to keep data
      - ./sqls/init.sql:/docker-entrypoint-initdb.d/init.sql
      - pgdata:/var/lib/postgresql/data

  # rabbitMQ
  rabbitmq:
    image: rabbitmq:3.9
