# Generated by Django 3.2.8 on 2021-10-19 08:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shopapp', '0002_auto_20211019_0818'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='shop',
            name='product',
        ),
        migrations.AddField(
            model_name='shop',
            name='products',
            field=models.ManyToManyField(to='shopapp.Product'),
        ),
    ]
