# Generated by Django 3.2.8 on 2021-10-20 08:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shopapp', '0002_alter_product_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productcategory',
            name='category',
            field=models.CharField(choices=[('clothing', 'Clothing'), ('shoes', 'Shoes'), ('sport', 'Sport')], max_length=20),
        ),
    ]
