# Generated by Django 3.2.8 on 2021-11-24 10:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop_api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shopinfo',
            name='shop_name',
            field=models.CharField(max_length=50, unique=True),
        ),
    ]
