# Generated by Django 3.2.8 on 2021-11-04 14:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop_api', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='shop',
            old_name='user',
            new_name='owner',
        ),
    ]
